fakk/api/invoices/routes.py
from flask import Blueprint, request, jsonify, render_template, url_for
from flask_login import login_required, current_user
from fakk.forms import CreateInvoice, ChangeInvoice
#from swish_qr_gen import swishQR, swishQRbase64
from fakk.utils.swish_qr_gen import swishQR, swishQRbase64
from flask_weasyprint import HTML, render_pdf
from fakk import mail
import io
from fakk import db
from fakk.models import User, Invoice

invoices_api = Blueprint('invoices_api', __name__)

#, url_prefix='/api'

@invoices_api.route('/claim')
@login_required
def claim():
	print('going to claim page')
	return render_template("claim.html", claim=True)

@invoices_api.route('/invoice/create-emb=<embedded>', methods=['GET', 'POST'])
@login_required
def createInvoice(embedded):
	print("invoice")
	form = CreateInvoice()
	#form.receiver.choices = [(g.frienduserid, User.query.filter_by(userid=g.frienduserid).first().username) for g in Relationship.query.filter_by(userid=current_user.userid, statusid=3).all()]
	#form.receiver.choices = [(g.frienduserid, g.rel_receiver.username) for g in current_user.get_friends()]
	choices = [(-1, 'Select receiver')]
	print(choices)
	for i in current_user.get_friends():
		choices.append((i.frienduserid, i.rel_receiver.username))
	#choices.append((g.frienduserid, g.rel_receiver.username) for g in current_user.get_friends())
	print(choices)
	form.receiver.choices = choices
	#form.receiver.choices = ([(g.frienduserid, g.rel_receiver.username) for g in current_user.get_friends()])
	if embedded=="false":
		emb=False
	else:
		emb=True
	#print("username: ", form.username.data)
	if form.validate_on_submit():
		invoice = Invoice(
			amount=form.amount.data,
			description=form.description.data,
			userid=current_user.userid,
			receiving_user=form.receiver.data
			
			)
		print(invoice)
		db.session.add(invoice)
		db.session.commit()
		print(form.receiver.data, form.description.data, form.amount.data)
		print({'message' : "Invoice sent"})
		return {'message' : "Invoice sent"}
	return render_template('invoice.html', form=form, embedded=emb)

@invoices_api.route('/invoice/change<invoice>', methods=['GET', 'POST'])
@login_required
def changeInvoice(invoice):

	form = ChangeInvoice()
	
	emb=True
	invoice_to_change=Invoice.query.filter_by(invoiceid=invoice).first()
	print(invoice_to_change)
	#print("username: ", form.username.data)
	if form.validate_on_submit():
		invoice_to_change.update(form.description.data, form.amount.data)
		print(invoice_to_change)
		#db.session.add(invoice)
		#db.session.commit()
		#print(form.receiver.data, form.description.data, form.amount.data)
		print({'message' : "Invoice changed"})
		return {'message' : "Invoice changed"}
	return render_template('invoice.html', form=form, embedded=emb, change=True, invoice=invoice_to_change)

@invoices_api.route('/invoices/renderpdf/<inv>')
@login_required
def renderpdf(inv):
	username=current_user.username
	invoice = getInvoice(inv).get_json()
	payee = User.query.filter_by(userid=invoice['invoice']['receiverid']).first()
	sender = User.query.filter_by(userid=invoice['invoice']['senderid']).first()
	#print('invoice_json: ', invoice)
	#print('payee: ', payee)
	#print('sender: ', sender)
	if(invoice['success']):
		

		swish_qr_base64=swishQRbase64(sender.phone, invoice['invoice']['amount'], invoice['invoice']['description'])
		print_html = render_template('invoice_pdf_template.html', username=sender.username, invoice=invoice['invoice'], qrCode_base64=swish_qr_base64, css1=url_for('static', filename='invoice_pdf/boilerplate.css'), css2=url_for('static', filename='invoice_pdf/main.css'), css3=url_for('static', filename='invoice_pdf/normalize.css'))
		
		
		return render_pdf(HTML(string=print_html), download_filename='invoice'+str(invoice['invoice']['invoiceid'])+'.pdf')
	else:

		return {'message' : invoice['message']}
	
@invoices_api.route('/invoices/email/<inv>')
@login_required
def email_invoice(inv):
	print(current_user.userid)
	print(inv)
	invoice = getInvoice(inv).get_json()
	if(invoice['success']):
		payee = User.query.filter_by(userid=invoice['invoice']['receiverid']).first()
		sender = User.query.filter_by(userid=invoice['invoice']['senderid']).first()

		if payee.email:
			print('payee email: ', payee.email)
			if current_user.phone:
				
				username=current_user.username
				swish_qr_base64=swishQRbase64(sender.phone, invoice['invoice']['amount'], invoice['invoice']['description'])
				html = HTML(string=render_template('invoice_pdf_template.html', username=sender.username, invoice=invoice['invoice'], qrCode_base64=swish_qr_base64, css1=url_for('static', filename='invoice_pdf/boilerplate.css'), css2=url_for('static', filename='invoice_pdf/main.css'), css3=url_for('static', filename='invoice_pdf/normalize.css')))
				pdf = io.BytesIO(html.write_pdf())
				msg = Message("Du har blivit fakkad :)",
			                  sender="bjorncarlsson87@gmail.com",
			                  recipients=[payee.email])
				msg.body = "Du har blivit fakkad, se bifogat" 
				msg.attach('invoice.pdf', 'application/pdf', data=pdf.read())
				mail.send(msg)
				return {'message' : "Email sent!"}
			else:
				return {'message' : "You have no phone number registred which is needed to genarate swish QRcode :("}
		else:
			return {'message' : "Payee has no email address registered :("}
	else:

		return {'message' : invoice['message']}	

#TO BE MOVED TO API ROUTES

@invoices_api.route('/invoice/getinvoices')
@login_required
def getInvoices():
	print(current_user.userid)
	received = []
	sent = []
	
	for i in current_user.invoice_receiver:
		
		r = {
		'invoiceid' : i.invoiceid,
		'senderid' : i.userid,
		'sender' : i.sender.username,
		'description' : i.description,
		'amount' : i.amount,
		'invoicestatus' : i.statusid,
		'message' : i.message
		}
		#print(r)
		received.append(r)
	
	for i in current_user.invoice_sender:
		
		r = {
		'invoiceid' : i.invoiceid,
		'recieverid' : i.frienduserid,
		'receiver' : i.receiver.username,
		'description' : i.description,
		'amount' : i.amount,
		'invoicestatus' : i.statusid,
		'message' : i.message
		}
		
		sent.append(r)

	return jsonify({
		'received' : received,
		'sent' : sent
		})

@invoices_api.route('/invoice/getinvoice<invoiceid>')
@login_required
def getInvoice(invoiceid):

	print('currentuserID ', current_user.userid)
	print('invoiceid to look for ',invoiceid)
	
	invoice_to_get=Invoice.query.filter_by(invoiceid=invoiceid).first()
	
	if(invoice_to_get):
		if(invoice_to_get.userid==current_user.userid or invoice_to_get.frienduserid==current_user.userid):
			invoice = {
				'invoiceid' : invoice_to_get.invoiceid,
				'receiverid' : invoice_to_get.frienduserid,
				'receiver' : invoice_to_get.receiver.username,
				'description' : invoice_to_get.description,
				'amount' : invoice_to_get.amount,
				'invoicestatus' : invoice_to_get.statusid,
				'message' : invoice_to_get.message,
				'senderid' : invoice_to_get.userid,
				'sender' : invoice_to_get.sender.username,
				'duedate' : invoice_to_get.date_due,
				'createddate' : invoice_to_get.date_created,
				'version' : invoice_to_get.invoice_version
				}

			return jsonify({
					'success' : True,
					'invoice' : invoice
					})
		return jsonify({
		'success' : False,
		'message' : 'not authorized'
		})
	return jsonify({
		'success' : False,
		'message' : 'no invoice found'
		})


@invoices_api.route('/invoice/pay', methods=['GET', 'POST'])
@login_required
def payInvoice():

	if request.method == 'POST':
		data = request.get_json()
		print(data)
		Invoice.query.filter_by(invoiceid=data['InvoiceID']).first().change_status(2)

	

	return jsonify({
		'message' : 'invoice marked as payed'
		})

@invoices_api.route('/invoice/reject', methods=['GET', 'POST'])
@login_required
def rejectInvoice():

	if request.method == 'POST':
		data = request.get_json()
		print(data)
		invoice_to_reject=Invoice.query.filter_by(invoiceid=data['InvoiceID']).first()
		invoice_to_reject.reject(data['message'])
	

		return jsonify({
			'message' : 'invoice marked as rejected'
			})
	return {'message' : "No post in reject invoice"}	

@invoices_api.route('/invoice/remove', methods=['GET', 'POST'])
@login_required
def removeInvoice():
	print("invoice")

	if request.method == 'POST':
		data = request.get_json()

		invoice_to_delete=Invoice.query.filter_by(invoiceid=data['InvoiceID']).first()
		invoice_to_delete.delete()
		return {'message' : "invoice removed"}

	return {'message' : "No post in accept friend request"}	

fakk/api/relations/routes.py
from flask import Blueprint, request, jsonify, render_template, flash, url_for
from flask_login import login_required, current_user
from fakk import db
from fakk.models import User, Relationship

relations_api = Blueprint('relations_api', __name__)


@relations_api.route('/user')
@login_required
def user():
	print('going to user page')
	return render_template("user.html", user=True)

@relations_api.route('/users/<query>')
@login_required
def users(query):
	print(current_user.userid)
	#from models import User
	if query == '*':		
		return jsonify([i.serialize() for i in User.query.filter(current_user.username!=User.username).all()])
	search = "%{}%".format(query)
	return jsonify([i.serialize() for i in User.query.filter(User.username.ilike(search), current_user.username!=User.username).all()])


#route to send a friend request from current user to selected user i request mestod = POST. If request method= GET then friends status string is returned
@relations_api.route('/relations/request', methods=['GET', 'POST'])
@login_required
def friendrequest():
	#from fakk import db
	#from models import User, Relationship
	if request.method == 'POST':
		data = request.get_json()
		if Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid, statusid=3).first():
			return {'message' : "already friends"}
		if Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid, statusid=2).first():
			return {'message' : "friend request already sent, wait for confirmation"}
		if Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid, statusid=1).first():
			return {'message' : "friend request pending. Either accept or reject."}
		else:
			user_sending_req = Relationship(user=current_user.userid,
				receiving_user=data['FriendUserID'],
				status=1)
			user_receiving_req = Relationship(user=data['FriendUserID'],
				receiving_user=current_user.userid,
				status=2)
			#print(new_rel.userid)
			db.session.add(user_sending_req)
			db.session.add(user_receiving_req)
			db.session.commit()
			return {"message": 'friend request sent from '+str(current_user.username)+' to '+str(User.query.filter_by(userid=data['FriendUserID']).first().username)}

	return {'message' : "No post in friend request"}


@relations_api.route('/relations/accept', methods=['GET', 'POST'])
@login_required
def accept_friendrequest():
	#from models import User, Relationship
	if request.method == 'POST':

		data = request.get_json()
		print(data)
		if(Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid, statusid=1).first()):
			Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid).first().accept_req()
			Relationship.query.filter_by(userid=current_user.userid, frienduserid=data['FriendUserID']).first().accept_req()
			return {'message' : "friendrequest acepted"}
		else:
			return {'error' : "there was no friend request"}

		return {"message": 'friend request sent from '+str(current_user.username)+' to '+str(User.query.filter_by(userid=data['FriendUserID']).first().username)}

	return {'message' : "No post in accept friend request"}



@relations_api.route('/relations/reject', methods=['GET', 'POST'])
@login_required
def reject_friendrequest():
	#from models import User, Relationship
	if request.method == 'POST':
		data = request.get_json()
		print(data)
		if(Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid, statusid=1).first()):
			Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid).first().delete()
			Relationship.query.filter_by(userid=current_user.userid, frienduserid=data['FriendUserID']).first().delete()
			return {'message' : "friendrequest rejected"}
		else:
			return {'error' : "there was no friend request"}

		return {"message": 'friend request sent from '+str(current_user.username)+' to '+str(User.query.filter_by(userid=data['FriendUserID']).first().username)}

	return {'message' : "No post in accept friend request"}

@relations_api.route('/relations/withdraw', methods=['GET', 'POST'])
@login_required
def withdraw_friendrequest():
	#from models import User, Relationship
	if request.method == 'POST':

		data = request.get_json()
		print(data)
		if(Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid, statusid=3).first()):
			return {'message' : "request already accepted"}
		if(Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid, statusid=2).first()):
			#print(user.username)
			Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid).first().delete()
			Relationship.query.filter_by(userid=current_user.userid, frienduserid=data['FriendUserID']).first().delete()
			return {'message' : "friendrequest withdrawn"}
		else:
			return {'error' : "there was no friend request",
					'message' : "already rejected"}

		return {"message": 'friend request sent from '+str(current_user.username)+' to '+str(User.query.filter_by(userid=data['FriendUserID']).first().username)}

	return {'message' : "No post in accept friend request"}



@relations_api.route('/relations/unfriend', methods=['GET', 'POST'])
@login_required
def unfriend():
	#from models import User, Relationship
	if request.method == 'POST':

		data = request.get_json()
		print(data)
		if(Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid, statusid=3).first()):
		#if(current_user.rel_sender.frienduserid=:
			#print(user.username)
			Relationship.query.filter_by(userid=data['FriendUserID'], frienduserid=current_user.userid, statusid=3).first().delete()
			Relationship.query.filter_by(userid=current_user.userid, frienduserid=data['FriendUserID'], statusid=3).first().delete()
			return {'message' : "friend removed"}
		else:
			return {'error' : "there was no friend request"}

		return {"message": 'friend request sent from '+str(current_user.username)+' to '+str(User.query.filter_by(userid=data['FriendUserID']).first().username)}

	return {'message' : "No post in accept friend request"}	

@relations_api.route('/relations/getrelations')
@login_required
def relations():
	#from models import User
	
	results = []
	friends =[]
	request_by_me = []
	request_to_me = []
	blocked_by_me = []
	blocked_to_me = []
	for i in current_user.friend_requester:

		r = {
		'id' : i.frienduserid,
		'username' : i.rel_receiver.username,
		'status' : i.statusid
		}

		if i.statusid == 3:
			friends.append(r)
		elif i.statusid == 1:
				request_by_me.append(r)
		elif i.statusid == 2:
				request_to_me.append(r)
		elif i.statusid == 4:
			blocked_by_me.append(r)
		elif i.statusid == 5:
			blocked_to_me.append(r)

	return jsonify({
		'friends' : friends,
		'request_by_me' : request_by_me,
		'request_to_me' : request_to_me,
		'blocked_by_me' : blocked_by_me,
		'blocked_to_me' : blocked_to_me,
		})

fakk/site/main/routes.py
from flask import render_template, Blueprint, flash, url_for, Markup, redirect
from flask_login import login_required, current_user


main = Blueprint('main', __name__)


# our beloved index page, here is where the magic will happen
@main.route('/')
@login_required
def home():
	#print(current_user)
	if not current_user.email:
		flash(Markup('TIPS: Ange en E-mail till ditt konto. Då kan du maila fakturor till andra. Du gör det <a href="%s" class="alert-link">här</a>') % url_for('user.profile'), category='warning')
	elif not current_user.confirmed_email:
		flash('TIPS: du behöver bekräfta din E-mail, kolla din email efter en länk eller gå till dina uppgifter och skicka efter en ny', category='warning')
	if not current_user.phone:
		flash(Markup('TIPS: Ange ett telefonnummer till ditt konto. Då kan du låta andra betala dina fakturor med Swish och skicka fakturor med SMS. Du gör det <a href="%s" class="alert-link">här</a>') % url_for('user.profile'), category='warning')
	elif not current_user.confirmed_phone:
		flash('TIPS: du behöver bekräfta ditt telefonnummer, gå till din profil och ange koden i smset eller skicka efter en ny kod', category='warning')
	return render_template("index.html", invoices_rec=len(current_user.invoice_receiver), invoices_sent=len(current_user.invoice_sender))

# if you are not logged in you will be directed to here
@main.route('/welcome')
def welcome():
	#print(current_user)
	#return render_template("welcome.html", user=current_user)
	return render_template("welcome.html")

@main.route('/<invoice_token>/')

def invoice_site(invoice_token):
	
	return redirect(url_for('invoices.view_open_invoice_site', invoice_token=invoice_token))

@main.route('/calculator')
@login_required
def calculator():
	#print(current_user)
	

	return render_template("calculator.html")

fakk/templates/calculator.html
{% extends "base.html" %}
{% block content %}

      <form name="calculator" class="form-group">
         <table>
            <tr>
               <td colspan="4">
                  <input type="text" class="form-control input-lg" name="display" id="display" disabled>
               </td>
            </tr>
            <tr>
               <td><input type="button" class="btn btn-primary btn-circle btn-md" name="one" value="1" onclick="calculator.display.value += '1'"></td>
               <td><input type="button" class="btn btn-primary btn-circle btn-md"name="two" value="2" onclick="calculator.display.value += '2'"></td>
               <td><input type="button" class="btn btn-primary btn-circle btn-md"name="three" value="3" onclick="calculator.display.value += '3'"></td>
               <td><input type="button" class="operator btn btn-warning btn-circle btn-md" name="plus" value="&#43;" onclick="calculator.display.value += '+'"></td>
            </tr>
            <tr>
               <td><input type="button" class="btn btn-primary btn-circle btn-md"name="four" value="4" onclick="calculator.display.value += '4'"></td>
               <td><input type="button" class="btn btn-primary btn-circle btn-md"name="five" value="5" onclick="calculator.display.value += '5'"></td>
               <td><input type="button" class="btn btn-primary btn-circle btn-md"name="six" value="6" onclick="calculator.display.value += '6'"></td>
               <td><input type="button" class="operator btn btn-warning btn-circle btn-md" name="minus" value="&#8722;" onclick="calculator.display.value += '-'"></td>
            </tr>
            <tr>
               <td><input type="button" class="btn btn-primary btn-circle btn-md"name="seven" value="7" onclick="calculator.display.value += '7'"></td>
               <td><input type="button" class="btn btn-primary btn-circle btn-md"name="eight" value="8" onclick="calculator.display.value += '8'"></td>
               <td><input type="button" class="btn btn-primary btn-circle btn-md"name="nine" value="9" onclick="calculator.display.value += '9'"></td>
               <td><input type="button" class="operator btn btn-warning btn-circle btn-md" name="times" value="&#215;" onclick="calculator.display.value += '*'"></td>
            </tr>
            <tr>
               <td><input type="button" class="btn btn-danger btn-circle btn-md" id="clear" name="clear" value="C" onclick="calculator.display.value = ''"></td>
               <td><input type="button" class="btn btn-primary btn-circle btn-md" name="zero" value="0" onclick="calculator.display.value += '0'"></td>
               <td><input type="button" class="btn btn-success btn-circle btn-md" name="doit" value="&#61;" onclick="calculator.display.value = eval(calculator.display.value)"></td>
               <td><input type="button" class="operator btn btn-warning btn-circle btn-md" name="div" value="&#247;" onclick="calculator.display.value += '/'"></td>
            </tr>
         </table>
      </form>

{% endblock %}

fakk/templates/friends.html
{% extends "base.html" %}
{% block content %}

<h2>{{title}}</h2>
<br>
<nav class="navbar navbar-light bg-light justify-content-between">
  <form class="form-inline" action="{{ url_for('contacts.friend_search')}}" method="POST">
    <input class="form-control mr-sm-2" type="search" name="user_search" id="user_search" placeholder="Sök efter kontakter" aria-label="Search">
    <button class="mr-2 btn btn-sm btn-primary my-2 my-sm-0" type="submit">Sök</button>

  </form>
</nav>
<br></br>
{% if searchresult %}
<h3>Sökresultat</h3>
{% for friend in searchresult %}

<article class="media content-section">
  <img class="rounded article-img" src="{{ url_for('static', filename='person.png') }}">
  <div class="media-body">
    <div class="article-metadata">

     
      <small class="text-muted">{%if friend.status == 0 %}Ej vänner än{% elif friend.status == 1 %}Väntar på svar{% elif friend.status == 2 %}Du har en förfrågan{% elif friend.status == 3 %}Vänner{% endif %}</small>
    </div>
    <h4><a class="article-title" href="{{ url_for('main.home') }}">{{ friend.user.username }}</a></h4>
    
    {%if friend.status == 0 %}
    <a class="mr-2 btn btn-sm btn-primary" href="{{ url_for('contacts.friendrequest_site', friend_id=friend.user.userid)}}">Skicka vänförfrågan</a>
    {% elif friend.status == 1 %}
    <a class="mr-2 btn btn-sm btn-danger" href="{{ url_for('contacts.withdraw_friendrequest_site', friend_id=friend.user.userid)}}">Dra tillbaka</a>
    {% elif friend.status == 2 %}
    <a class="mr-2 btn btn-sm btn-primary" href="{{ url_for('contacts.accept_friendrequest_site', friend_id=friend.user.userid)}}">Acceptera!</a>
    <a class="mr-2 btn btn-sm btn-warning" href="{{ url_for('contacts.reject_friendrequest_site', friend_id=friend.user.userid)}}">Avböj!</a>
    {% elif friend.status == 3 %}
    <a class="mr-2 btn btn-sm btn-danger" href="{{ url_for('contacts.unfriend_site', friend_id=friend.user.userid)}}">Ta bort</a>
    {% endif %}
  </div>
</article>
{% endfor %}
{% endif %}


{%if friends|selectattr('statusid', 'equalto', 2)|list|length > 0%}
<h3>Förfrågningar till dig</h3>
{% for friend in friends %}

{% if friend.statusid == 2 %}

<article class="media content-section">
  <img class="rounded article-img" src="{{ url_for('static', filename='person.png') }}">
  <div class="media-body">
    <div class="article-metadata">
<h4><a class="article-title" href="{{ url_for('main.home') }}">{{ friend.rel_receiver.username }}</a></h4>
    </div>
    
    
    <a class="mr-2 btn btn-sm btn-primary" href="{{ url_for('contacts.accept_friendrequest_site', friend_id=friend.rel_receiver.userid)}}">Acceptera!</a>
    <a class="mr-2 btn btn-sm btn-warning" href="{{ url_for('contacts.reject_friendrequest_site', friend_id=friend.rel_receiver.userid)}}">Avböj!</a>
  </div>
</article>
{% endif %}
{% endfor %}
{% endif %}
<br>
{%if friends|selectattr('statusid', 'equalto', 1)|list|length > 0%}
<h3>Förfrågningar från dig</h3>
{% for friend in friends %}
{% if friend.statusid == 1 %}

<article class="media content-section">
  <img class="rounded article-img" src="{{ url_for('static', filename='person.png') }}">
  <div class="media-body">
    <div class="article-metadata">
      
    <h4><a class="article-title" href="{{ url_for('main.home') }}">{{ friend.rel_receiver.username }}</a></h4> 
    </div>
    
   
    <a class="mr-2 btn btn-sm btn-danger" href="{{ url_for('contacts.withdraw_friendrequest_site', friend_id=friend.rel_receiver.userid)}}">Dra tillbaka</a>
  </div>
</article>
{% endif %}
{% endfor %}
{% endif %}
{%if friends|selectattr('statusid', 'equalto', 3)|list|length > 0%}
<h3>Vänner</h3>
{% for friend in friends %}
{% if friend.statusid == 3 %}
<article class="media content-section">
  <img class="rounded article-img" src="{{ url_for('static', filename='person.png') }}">
  <div class="media-body">
    <div class="article-metadata">
      
    <h4><a class="article-title" href="{{ url_for('main.home') }}">{{ friend.rel_receiver.username }}</a></h4>  
    </div>
    
    
    <a class="mr-2 btn btn-sm btn-danger" href="{{ url_for('contacts.unfriend_site', friend_id=friend.rel_receiver.userid)}}">Ta bort</a>
  </div>
</article>
{% endif %}
{% endfor %}
{%else%}
<h3>Inga vänner än</h3>
{% endif %}

{% endblock content %}

fakk/templates/index.html
{% extends "base.html" %}
{% block content %}





<p>Du har {{invoices_sent}} skickade fakturor</p>
<p>Du har {{invoices_rec}} mottagna fakturor</p>



<br>
{% if current_user.username == 'bjorn' %}
<b>Old version links</b><br>
<small>
	<a href="{{ url_for('main.calculator') }}">Miniräknare</a><br>
	<a href="/">Home</a><br>
	<a href="#" id="user">Friends and Foes</a><br>
	<a href="#" id="claim">Claims and Debts</a><br>
	<a href="{{ url_for('relations_api.user') }}">Kontakter(old)</a><br>
	<a href="{{ url_for('invoices_api.claim') }}">Fakturor(old)</a><br></small>
	<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
	<script>
		$("#user").on("click", function(){
			$("#sub-menu").load("{{ url_for('relations_api.user') }}");
		});
		$("#claim").on("click", function(){
			$("#sub-menu").load("{{ url_for('invoices_api.claim') }}");
		});
	</script>
{%endif%}
	<div id="sub-menu">

		

	</div>
	<br>
</div>
{% if user %} 

{% include 'user.html' %}

{% endif %}
{% if claim %} 

{% include 'claim.html' %}

{% endif %}


{% endblock %}

fakk/templates/invoice_email_template.html
<html>
<body>
	<h1> Faktura från {{ username }}</h1>
	<br>
	<p> Du har blivit (duktigt) fakturerad</p>

	<br>
	<table>
		<tr><td style="text-align:left">Description</td><td style="text-align:left">{{invoice.description}}</td></tr>
		<tr><td style="text-align:left">Sender</td><td style="text-align:left">{{invoice.sender}}</td></tr>
		<tr><td style="text-align:left">Receiver</td><td style="text-align:left">{{invoice.receiver}}</td></tr>
		<tr><td style="text-align:left">Amount</td><td style="text-align:left">{{invoice.amount}}</td></tr>
		<tr><td style="text-align:left">Created date</td><td style="text-align:left">{{invoice.createddate}}</td></tr>
		<tr><td style="text-align:left">Due date</td><td style="text-align:left">{{invoice.duedate}}</td></tr>
		<tr><td style="text-align:left">Version</td><td style="text-align:left">{{invoice.version}}</td></tr></p>
	</table>
	<table><tr><td style=" width:20px; height:20px">
		<img src="data:image/svg+xml;base64,{{qrCode_base64}}" width="100" height="100" id="logo"></img></td></tr>

	</table>
</body>
</html>

fakk/templates/welcome.html
{% extends "base.html" %}
{% block content %}

<h1>Välkommen till fakk!</h1>
<br>
<br>
<P>fakk. är det transaktionella sättet att umågs.</P>
<br>
<p>När dina vänner säger "du skickar en faktura va" kan du nu säga "javisst!"</p>
<br>
<P>fakk. var coolt innan social distansering var en grej.</P>
<br>
<p>Logga in eller skapa konto ovan. Trevlig helg och tack för kaffet!</p>


{% endblock %}